version: 2

sphinx:
  fail_on_warning: true


python:
  install:
    - requirements: docs/docs_requirements.txt
    - method: pip
      path: .


formats:
  - pdf


submodules:
  include: all
  recursive: true




