version: 2

sphinx:
  fail_on_warning: true



conda:
  channel: conda-forge
  environment: conda.txt

python:
  install:
    - method: pip
      path: .


formats:
  - pdf


submodules:
  include: all
  recursive: true




