name: pyinteraph-env
channels:
    - conda-forge
dependencies:
    - python=3.7
    - attrs=20.3.0
    - biopython=1.78
    - cycler=0.10.0
    - decorator=4.4.2
    - cython=0.29.23
    - GridDataFormats=0.5.0
    - gsd=2.4.2
    - importlib-metadata=4.0.1
    - iniconfig=1.1.1
    - joblib=1.0.1
    - kiwisolver=1.3.1
    - matplotlib=3.3.4
    - MDAnalysis=1.1.1
    - mmtf-python=1.1.2
    - mock=4.0.3
    - networkx=2.5.1
    - numpy=1.20.2
    - packaging=20.9
    - pandas=1.3.5
    - Pillow=9.0.0
    - py=1.10.0
    - pytest=6.2.3
    - python-dateutil=2.8.1
    - pytz=2021.1
    - scipy=1.7.3
    - seaborn=0.11.1
    - six=1.15.0
    - toml=0.10.2
    - tqdm=4.60.0
    - typing-extensions=3.7.4.3
    - zipp=3.4.1
