name: AlloViz
channels:
  - conda-forge
dependencies:
  - pymol-open-source
  - ambertools
  - pip
  - pip:
      - -r ../pip_requirements.txt
      - ipywidgets=7.7.5
      - jupyterlab=3.6.5