name: Python Package using Conda

on:
  push:
    branches:
      - reg_test
      - fix_submodules

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }} #true
    strategy:
      matrix:
        os: ["ubuntu", "macos"] #, "windows"]
        experimental: [false]
        include:
          - os: "windows"
            experimental: true
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive


    # INSTALL TCL 8.5 IN WINDOWS BC APPARENTLY THE CONDA THING DOESN'T WORK?


    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: anaconda-client-env
        use-mamba: true
    - name: Process environment file
      run: python dev/cme_parser/create_env.py -i dev/dev_env.yml.meta -o dev/dev_env_out.yml -p -v so ${{ matrix.os }}
      # run: |
      #   wget https://raw.githubusercontent.com/silvanmelchior/cme_parser/master/create_env.py
      #   python create_env.py -i dev/dev_env_meta.yml -o dev/dev_env_out.yml -p
      # uses: suisei-cn/actions-download-file@v1.3.0
      # id: downloadfile  # Remember to give an ID if you need the output filename
      # with:
      #   url: "https://raw.githubusercontent.com/silvanmelchior/cme_parser/master/create_env.py"
      #   target: create_env.py
    - name: Cache Conda env
      uses: actions/cache@v3
      with:
        path: ${{ env.CONDA }}/envs
        key:
          conda-${{ runner.os }}--${{ runner.arch }}-${{ hashFiles('dev/dev_env_out.yml') }}-${{ env.CACHE_NUMBER }}
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      id: cache
    - name: Update environment
      run:
        mamba install -n anaconda-client-env -c conda-forge "tk>=8.5,<8.6" --force-reinstall -y
        mamba env update -n anaconda-client-env -f dev/dev_env_out.yml
      if: steps.cache.outputs.cache-hit != 'true'

    # - uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     activate-environment: test
    #     channels: conda-forge
    #     environment-file: dev/dev_env.yml
    #     # python-version: "3.10"
    #     auto-activate-base: false
    - name: Install AlloViz
      run: pip install .

    # - name: Lint with flake8
    #   run: |
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest test