name: Python Package using pip

on:
  push:
    branches:
      - reg_test
      - fix_submodules

jobs:
  miniconda:
    name: pip ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }} #true
    # python-version: "3.10"
    strategy:
      matrix:
        os: ["ubuntu", "macos"] #, "windows"]
        experimental: [true] # CHANGE TO FALSE WHEN EVERYTHING RUNS
        include:
          - os: "windows"
            experimental: true

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: msys2/setup-msys2@v2
      if: matrix.os == 'windows'
      with:
        update: true
        install: >-
          zlib
        # https://github.com/msys2/MSYS2-packages/blob/12598003a2a68c7e3187d76cb9ec3588a07a5c95/tcl/PKGBUILD

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.6"
        cache: "pip"
        cache-dependency-path: dev/dev_env.txt


    # - name: Cache pip deps
    #   uses: actions/cache@v3
    #   with:
    #     path: ${{ env.pythonLocation }}
    #     key:
    #       ${{ env.pythonLocation }}-pip-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('dev/dev_env.txt') }}-${{ env.CACHE_NUMBER }}
    #   env:
    #     # Increase this value to reset cache if has not changed
    #     CACHE_NUMBER: 0
    #   id: cache


    - name: Install dependencies
      run: |
        python -m pip install -U --upgrade-strategy eager pip
        pip install -U --upgrade-strategy eager setuptools "numpy>=1.22.4,<1.22.5"
        pip install -r dev/dev_env.txt

    # - name: Update environment
    #   run:
    #     mamba env update -n anaconda-client-env -f dev/dev_env_out.yml
    #   if: steps.cache.outputs.cache-hit != 'true'

    - name: Install AlloViz
      run: pip install .

    # - name: Lint with flake8
    #   run: |
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest test